- add a retry loop for the discogs job to avoid collisions when pushing

diff --git a/.github/workflows/discogs.yml b/.github/workflows/discogs.yml
--- a/.github/workflows/discogs.yml
+++ b/.github/workflows/discogs.yml
@@ -24,7 +24,15 @@ jobs:
         python3 discogs.py -store '${{matrix.store}}' -key '${{secrets.SERVICE_ACCOUNT}}' -discogs-key '${{secrets.DISCOGS_KEY}}' -releases 1024 -searches 100
         git config user.name github-actions
         git config user.email github-actions@github.com
-        git add .
-        git commit -m "- update '${{matrix.store}}' releases" || true
-        git pull --rebase
-        git push origin HEAD:main
+
+        for i in {1..5}; do
+          git add .
+          git commit -m "- update '${{ matrix.store }}' releases" || true
+
+          if git pull --rebase && git push origin HEAD:main; then
+            break
+          fi
+
+          echo "Push failed, retrying ($i/5)..."
+          sleep 2
+        done
